config/routes.rb
Vikings::Application.routes.draw do

  get "/culture", to: "static_pages#culture"
  get "/gods", to: "static_pages#gods"
  get "/game_rules", to: "static_pages#game_rules"
  get "/timeline", to: "static_pages#timeline"
  get "/map", to: "static_pages#map"
  get "/asgard", to: "static_pages#asgard"
  get "/crew", to: "static_pages#crew"
  get "/homerules", to: "static_pages#homerules"
  root "static_pages#home"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def culture
  end

  def gods
  end

  def game_rules
  end

  def timeline
  end

  def map
  end

  def crew
  end

  def homerules
  end

  def asgard
  end

  def test
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<div id="footer">
  <div class="container">
    <p class="text-muted">
    Viikingid Dungeons and Dragons
    </p>
  </div>
</div>

app/views/layouts/_header.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-55905413-1', 'auto');
  ga('send', 'pageview');

</script>
<div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
  <div class="container">
    <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "Viikingid", root_path, id: "logo", class: "navbar-brand" %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><%= link_to "Maailm", root_path %></li>
        <li><%= link_to "Kultuur", culture_path %></li>
        <li><%= link_to "Jumalad", gods_path %></li>
        <li><%= link_to "Mängu reeglid", game_rules_path %></li>
        <li><%= link_to "Ajajoon", timeline_path %></li>
        <li><%= link_to "Selvarini kaart", map_path %></li>
        <li><%= link_to "Asgard kaart", '/assets/asgard_prison.jpg' %></li>
        <li><%= link_to "Meeskond", crew_path %></li>
        <li><%= link_to "Homerules", homerules_path %></li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Vikings</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render '/layouts/header'%>
<div class="container">
<%= yield %>
</div>
<%= render '/layouts/footer'%>
</body>
</html>

app/views/static_pages/crew.html.erb
<div class="center">
  <%= image_tag("crew.jpg") =%>
</div>
<h1>Meeskond Esimesed</h1>

<ul>
<li>Hunt; Inimene, Rogue</li>
<li>Kjell; Inimene, Cleric</li>
<li>Veurr; Dwarf, Fighter</li>
<strike><li>Jorr; Gnoom, Sorcerer - KIA - Head bit off by a human-like crocodile</li></strike>
</ul>

<p>
Sõjasaagi manifestid leiab <a href="https://docs.google.com/spreadsheets/d/1u49ZWM9mAMGzK_ymnBrPttXRSuRO7BuNUnTojnnRFKY/edit#gid=0">SIIT</a>
</p>

<h2>Lennuki meeskond</h2>
<p>
  <ul>
    <li>Theodore; Gnoom; Cleric 3; Paadiehitaja ja hooldaja, palvetab koos Kvjelliga ja aitab jumalateenistusi läbi viia</li>
    <li>Crixus; Inimene; Fighter 4; Supilinna jarl ja sõlmpunkt läbi kelle meeskonnale käske jagada</li>
    <strike><li>Tammiste; Inimene; Rogue 3. Hundi mentor, kes on nakatunud libahundi needusesse. Tunneb suurt häbi sellepärast ja otsib läänes surma. - Currently kidnapped by Lucifer</li></strike>
    <li>Daegmar; Inimene; Rogue 2. Hundi Õde, kes on nakatunud libahundi needusesse. Tunneb suurt häbi sellepärast aga loodab läänes ravi leida.</li>
    <li>Oddny; Päkapikk; Fighter 3; Sai surma vitriini lahti tehes ja hiljem äratati maagiaga ellu tagasi.</li>
    <li>Sibbi; Inimene; Fighter 3</li>
    <li>Adolf; Inimene; Fighter 2</li>
    <li>Adrian; Inimene; Fighter 2</li>
    <li>Agathe; Inimene; Fighter 2</li>
    <li>Brynka; Päkapikk; Fighter 2</li>
    <li>Caj; Inimene; Barbarian 2</li>
    <li>Erica; Inimene; Barbarian 2</li>
    <li>Erland; Inimene; Barbarian 2</li>
    <li>Erle; Inimene; Barbarian 2</li>
    <li>Grete; Päkapikk; Barbarian 2</li>
    <li>Gösta; Ork; Barbarian 2</li>
    <li><strike>Helgi; Inimene; Barbarian 3</strike>; <b>KIA kloostri raamatukogu lahingus</b></li>
    <li><strike>Britta; Päkapikk; Fighter 2</strike>; <b>KIA kloostri raamatukogu lahingus</b></li>
    <li><strike>Göran; Ork; Barbarian 2</strike>; <b>KIA kloostri raamatukogu  lahingus kääbikute ust valvates</b></li>
    <li><strike>Björn; Inimene; Fighter 2</strike>; <b>KIA Kääbiku armeega lahingus;</b></li>
    <li><strike>Lily Gnoom; Arcane adept 1; Jorri poolt treenitakse sisemist maagiat endas leidma</strike>; <b>KIA libahuntidega lahingus;</b></li>
    <li><strike>Abi; Inimene; Fighter 1</strike>; <b>KIA libahuntidega lahingus;</b></li>
    <li><strike>Alf; Inimene; Barbarian 1</strike>; <b>KIA libahuntidega lahingus;</b></li>
    <li><strike>Cnut; Inimene; Barbarian 1</strike>; <b>KIA libahuntidega lahingus;</b></li>
    <li><strike>Diarf; Inimene; Fighter 1</strike>; <b>KIA libahuntidega lahingus;</b></li>
    <li><strike>Snorri; Päkapikk; Barbarian 1</strike>; <b>KIA libahuntidega lahingus;</b></li>
    <li><strike>Thorstar; Päkapikk; Fighter 1</strike>; <b>KIA libahuntidega lahingus;</b></li>
  </ul>
</p>
<p>
  Laeva tüüp: <a href="http://en.wikipedia.org/wiki/Longship#Drekkar">Drekkar</a>, 20 sõudmis kohta.<br/>
  Max load: 15000 lb<br/>
  Max crew size 20<br/>
</p>

<h2>Müügi meeskond - Currently kidnapped by lucifer</h2>
<strike><p>
Kaupmees, kes aitab müüa Esimestel asju.
</p>
<p>
  <ul>
    <li>Alrik; Inimene; Expert 2; Kjelli isa ja kaupmees</li>
    <li>Astrid; Inimene; Expert 2; Kjelli ema ja käsitööline</li>
  </ul>
</p>
<p>
  Mundane asjad: 100% hinnaga<br/>
  Maagilised asjad: 25% hinnaga<br/>
  Võtab iga reid 1 osa lootist<br/>
  Hoiab endal seeri ja sõdureid palgal
</p>
</strike>

<strike>
<h2>Craftimis meeskond - currently MIA</h2>
<p>
  Aitavad esimestel luua maagilisi ja tavalisi itemeid
</p>
<p>
 <ul>
    <li>Tofu; Halfling; Wizard 5; Pime röövitud kääbikust laps, kes aitab Esimestele luua maagilisi esemeid</li>
    <li>Suur John; Halfling; Fighter ?; Tofu isa, kes tuli kaasa, et enda poissi kaitsta</li>
  </ul>
</p>
<p>
  Magic itemid 50% hinnaga<br/>
  Max caster level 5<br/>
  Only arcane spells up to level 3<br/>
</p>
</strike>
<h2>Nõuandjate meeskond</h2>
<p>
  Annavad Esimestele muudel viisidel nõu
</p>
<p>
 <ul>
    <li>Lina; Fey; Aitab Esimestel ohutult Veurri kodujuures, Ilove metsas liikuda. Ally to the first ones among the forest feys.</li>
    <li><strike>Frodo; Halflink; Cloistered cleric ?; Proovis Esimesi suunata võitlusesse suure põrgu kurjuse vastu ja andis nõus, kust leida infot ja teadmisi, kuidas seda teha</strike>; <b>KIA libahuntidega lahingus;</b></li>
  </ul>
</p>

app/views/static_pages/culture.html.erb
<div class="center">
  <%= image_tag("culture.jpg") =%>
</div>
<h1>Kultuur</h1>

<p>
Skandinaavialased on väga lärmakas, uhke, jäärapäine ja religioosne rahvas. Nad austavad jõudu, ausust ning endast targemaid. Nad põlastavad pettureid, nõrku ning reetureid.
</p>

<p>
Oma päevi veedavad nad tööd tehes ning treenides, pidevalt harjutades võitlemist. Õhtuid veedavad nad pidutsedes ja juues. Kui Skandinaavialastel omavahel tüli tekib, siis tihti lahendatakse küsimus jõudu kasutades. Rikkamatel viikingitel on oma talu ja maa. Vaesemad töötavad tihti sõdurite, valvuritena, sulastena või pühakodades. Suuremates auküsimustes kutsutakse üksteist välja duellile, mis tihti lõppeb ühe poole surmaga. Enamuse lihttöid teevad nende eest ära ohtrates kogustes orjad, mis on toodud idast. Kehtivad eri seadused Skandinaavialastele ning orjadele - orjadel põhimõtteliselt puuduvad igasugused õigused. Nende isand võib teha nendega mis iganes talle meeldib. Kuid see ei tähenda, et orje koheldaks väga halvasti. Aeg-ajalt mõni isand vabastab mõne orja, kuid endine ori töötab tihtipeale sama isanda juures vabatahtlikult edasi, lihtsalt ausa tasu eest.
</p>

<div class="center">
  <%= image_tag("woman_warrior.jpg") =%>
</div>

<p>
Skandinaavia rahvas on üks vähestest rahvastest maailmas, kus mehed ja naised on võrdsed. Skandinaavia naised võivad olla täpselt samamoodi Jarlid või valitsejad, ning tihtipeale ongi, ning keegi ei vaata sellele halvasti. Peredes on mehed ja naised võrdsel kohal. Naised harjutavad samamoodi võitluskunsti, nagu mehed ning peresisesed tülid lahendatakse täpselt samamoodi kakeldes, küll aga lõppevad need kaklused harvem teine-teise surmaga. Naisi võetakse ka reidimistele kaasa. Tõsi ta on - tihti on viikingid näinud vaenlasi hirmust tardumas, kui nad näevad nende poole jooksmas nais sõdurit. Kõige hirmuäratavamad on vaenlastele Valküürid - surmatoojad. Nende nägemise peale jookseb tihtilugu vastaspoole vägi koheselt igas suunas laiali.
</p>

<div class="center">
  <%= image_tag("valkyre.jpg") =%>
</div>

<p>
Kõige rohkem hirmutab vaenlasi viikingite juures tõsiasi, et nad ei karda surma. Viikingid taganevad, kui nad näevad, et lahingul ei ole mõtet, kuid nende silmis ei näe kunagi hirmu. Kõik viikingid tahavad surra lahingus. See on tee ja värav valhallasse - Skandinaavia jumalate taevasse. Need, kes surevad vanadusse, need ei saa valhalasse. Tihtipeale paluvad vanad mehed põlvili Jarlilt, et ta võtaks ta reidile kaasa, lihtsalt selleks, et tal oleks ka võimalus lahingus surra.
</p>

<p>
Viikingid on külmaverelised tapjad, kes ei näe midagi valesti selles, et nad teise tapavad. Kui vaenlane langetab relva paanikas, siis viiking võtab seda nõrkuse märgina, põlastab seda ja üldjuhul tapab ta kohapeal. Mõni õnnelik võetakse ka vangi ja eluaegseks orjaks.
</p>

<div class="center">
  <%= image_tag("old_man.jpg") =%>
</div>

app/views/static_pages/game_rules.html.erb
<div class="center">
  <%= image_tag("game_rules.jpg") =%>
</div>

<h1>Mängureeglid</h1>

<p>Mängu süsteem on <a href="http://www.d20pfsrd.com/">Pathfinder</a>, mis on põhimõtteliseld D&D 3.5 edasi arendus - ta lihtsustab seda, natuke balanseerib ja muudab mõne mõttetult keerulise(nt grapple ja turn undead) normaalseks. Kõik resursid pathfinderi kohta on olemas üleval antud lehel.</p>

<p>
Mängijad alustavad level 1.
</p>

<p>
Mängus lubatud rassid on Inimene, Päkapikk, Gnoom, Ork, Pool-Ork ja äärmisel juhul ka haldjas, kui hästi ära seletada, kuidas vabaks said.
</p>

<p>
Klassidest on lubatud kõik core klassid, peale Wizardi(sest viikingid ei oska lugeda, ega kirjutada). Lisaks võib uurida ka Base classe, aga räägime enne läbi. Aligment ei tohi olla good. Enamus viikineid on lawful netural/lawful evil.
</p>

<p>
Ability scorede teada saamiseks kasutage Point buy calculaatorit, näiteks
<a href="http://jody-white.com/ability-score-calculator/">siin</a>. Teil on kokku 20 punkti, mis ära jagada. Iga klassi juures on ka kirjas kui palju nad raha saavad, näiteks fighteril on: <i>Starting Wealth: 5d6 x 10 gp (average 175gp.) In addition, each character begins play with an outfit worth 10 gp or less</i>. See tähendab et fighter saab 175 gb. Keelatud on osta endale amb(crossbow) ning kellegil ei ole oskust seda kasutada, sest viikingitel ei ole ammu tehnoloogiat.
</p>
<div class="center">
  <%= image_tag("archer.jpg") =%>
</div>

<p>
Teie tegelastel on ka. <a href="http://www.d20pfsrd.com/traits">traitid</a>. <br/>
Alguses on: <br/>
Trait - <i>Viking fury - Character knows no fear: +2 to saves against fear and emotion affecting spells and abilities</i> <br/>
Drawback - <i>Illiterate - Character cannot read or write</i><br/>
Lisaks võib mängija kuni 2 traiti võtta veel, kuid peab iga traiti jaoks võtma ühe drawbacki. Siiski palun need eelnevalt minuga läbi arutada.
</p>

<p>

</p>

<p>
Kõik mängijad on alguses lähedased sõbrad, kes tihti näevad üksteist ja on ka koos reidimas käinud. Kõik võiksid saata mulle enda tegelase tagaloo. Mängijad võivad tagaloose kirjutada endale, et neil on ka maad ja talu koos orjadega. Kuid Jarl või kuningas ei tohi olla. Küll aga võib olla bastard son, põgenenud kuninga laps vms.
</p>

<div class="center">
  <%= image_tag("stand_as_one.jpg") =%>
</div>

app/views/static_pages/gods.html.erb
<div class="center">
  <%= image_tag("seer.jpg") =%>
</div>
<h1>Religioon</h1>

<p>
Skandinaavialastel on religioon väga tähtsal kohal. Nad usuvad ja elavad jumalate järgi. Enne tähtsate ja raskete otsuste tegemist käivad nad tihti prohveti juures nõu pidamas. Paljud tähtsad otsused, kaasa arvatud ka kohtuotsused, otsustatakse prohvetite, preestrite või oraaklite poolt. Igal Jarlil on oma isiklik prohvet olemas, kes aitab tal otse jumalatega rääkida.
</p>

<div class="center">
  <%= image_tag("celebrations.jpg") =%>
</div>

Iga 9 aasta tagant reisib igast viikingi külast suur osa rahvas pühapaikadesse üle Skandinaavia. Nad pidutsevad seal 9 päeva, mille jooksul saadetakse korda orgiaid, joomisi, tarbitakse mõistust mõjutavaid aineid ja unustatakse kõik igapäevased mured. Pidutstuste lõpus ohverdatakse 9 looma igast liigist, mida Skandinaavialased kasvatavad ning lisaks ka 9 vabatahtlikku, kes annavad end jumalatele. Sellega palutakse jumalalalt veel 9 aastat abi ja kaitset.

<div class="center">
  <%= image_tag("blood_eagle.jpg") =%>
</div>

Kõige hirmsam hukkamisviis, mis viikingid enda vaenlastele teevad on verikotkas. See on Viikingite teada kõige valusam hukkamisviis, mis üleüldse olemas. See tähendab seda, et hukatav pannakse põlvili ja seotakse kinni. Seejärel lüüakse tal seljatagant kirvega ribid katki, võetakse tal kopsud seljatagant välja ja pannakse üle ribide väljapoole rippuma. Ohver paistab sellisel juhul välja nagu kotkas. Hence the name blood eagle. Kui ohver suudab hukkamise ilma ühegi hääleta üle elada, siis tal on võimalus valhallasse saada.

<h2>Peamised jumalad</h2>

Lugege palun ise nende kohta, kes huvi pakuvad, täpsemat infot, aga siin on lühikokkuvõte et enda lemmik leida:
<br/><br/>
Odin - Jumalate jumal, sõja, luule, tarkuse ja surmajumal. Ta kogub Valhallasse lahingus langenud viikingeid, kes võitlevad temaeest Ragnarokis. Tal on oda, mis ei lähe kunagi mööda ja ta teeb tarkuse jaoks ohverdusi, kaasa arvatud enda silma.
<br/><br/>
Thor - Välgujumal, hiiglaste peamine vaenlane, Odini poeg. Kõige tugevam jumal. Relvaks vasar, mis alati ta kätte tagasi tuli
<br/><br/>
Loki - Varaste jumal ja trikitaja. Lapsendatud vend Odinile. Korraldas jumal Baldri surma. Ta on hiiglane ja kivi küljes kinni kuni Ragnarokini. Ragnarokis hiiglaste ja koletiste juht.
<br/><br/>
Freys - Ilma ja viljakuse jumal. Freya vend.
<br/><br/>
Freya - Seksi, viljakuse, sõja ja rikkuse jumal. Njordi tütar.
<br/><br/>
Forseti - Õigluse jumal.
<br/><br/>
Njord - Tuule ja mere jumal.
<br/><br/>
Tyr - Sõjajumal.

<h2>Ragnarok</h2>

Skandinaavia mütoloogias on Ragnarok maailmalõpp, kus Loki juhib kõiksugu põrgust tulnud hiiglased, koletised ja väljaheidetud jumalate vastu. Ragnaroki lõpuks põleb kogu maailm ära, seejärel upub see ära, mitmed suured jumala saavad surma, kaasa arvatud Odin, Thor, Tyr, Freys ja Loki. Kui maailm mere alt välja tuleb, on alles 2 inimest, kes saavad ülesandeks maailma uuesti üles ehitada.

<div class="center">
  <%= image_tag("ragnarok.jpg") =%>
</div>

app/views/static_pages/home.html.erb
<div class="center">
  <%= image_tag("raiders.jpg") =%>
</div>
<h1>Skandinaavialaste maailm</h1>
<p>
Skandinaavialaste elanud niikaua kuni keegi mäletab külmal maal, kus suved on lühikesed, vihmased ja talved pikad, külmad ning karmid. Seda maad kutsutakse Skandinaaviaks. See on rohkete jõgedega, tohutult kõrgete mägede ja vohavate metsade maa. Maailm ellu jäävad ainult tugevamad on Skandinaavialastest vorpinud tugevad, ilusad ning vastupidavad olendid. Selleks, et ellu jääda on nad pidanud muu maailma rahvastest olema oluliselt paindlikumad, avatuma meelega ning rohkem riske võtma.
<p>
<p>
Skandinaavialased elavad enamasti Skandinaavia mereäärsetel aladel. Kuid neil on tõsine probleem - nende maal on väga vähe lihtsasti haritavaid põllumaid. Skandinaavia Jarlid on pidevalt omavahel tülis ning sõdades, kuna nad võitlevad ühe või teise maatüki pärast. Paljud Jarlid on ka üritanud enda rahvaga tungida rohkem Skandinaavia südamesse, kuid seal asuvad hiigelsuured maagilised koletised. Mida sügavamale minna, seda hirmsamaid jõletisi leiab. Vähesed ellujääjad, kes on käinud sügaval sisemaal räägivad lugusid hiiglastest ja jõletisetest, kes on suuremad kui mäed ning mustast maagiast, mis ajab ka kõige tugevama mehe hulluks.
</p>

<div class="center">
  <%= image_tag("viking_beast.jpg") =%>
</div>

<p>Algusaastatel olid Skandinaavialased kõigest rahulikud talumehed. Kuid kui kerge maa hakkas otsa saama, siis see sundis Skandinaavialasi hakkama teisi väljapääse ellujäämiseks otsima. Esialgu hakati tegelema kaubandusega. Skandinaavia inimesed Alustasid kaubandussuhteid Päkapikkude, Gnoomide ning mägielukatega(Goblinitega). Nende abiga suudeti Skandinaavia veekogu äärsemad mäestikud ära asustada ja vallutada. Skandinaavias on ilmselt ainus ühiskond maailmas, kus Mägielukad ning päkapikud elavad rahus koos. Kuid mis veelgi üllatavam, Skandinaavialased leidsid sügavamalt Skandinaaviast Orkid. Ajalooliselt on kõik rahvused Orkidega sõtta läinud, kuid nii rasketes oludes ning ümbritsetuna maagilistest koletistest, said isegi Orkid aru, et neil on kasuliku Skandinaavialastega koostööd teha. Koos Orkide ja Skandinaavialastega on mitmeid sisemaa kindlusi püstitatud ning nende ümber maid harima hakatud. Kõige kuulsam on kõrge mäe otsas kuninglik loss Kivi, mis kahe nädala teekonna kaugusel Kattegatist - Viikingite pealinnast. Praeguseks ajaks on ei eristata enam Skandianaavialaste seas inimesi, Orke, Gnoome, Päkapikke ega Goblineid. Nad on kõik Skandinaavialased.</p>

<p>
Skandinaavialased lõid ka tihedad kaubandus sidemed idas asuvate Balti ja Russide maadega. Seal asusid mitmed rahvused, nende sead Metsahaldjad, Rus inimesed ja Tundra rahvas. Esialgu üritati tükk aega nendega kaubelda, kuid sealne rahvas vaatas tihtipeale Skandinaavialastele alla. Skandinaavialastele loodi mitmeid kaubandus barjääre, neile müüdi kaupa kallimalt ning vahel isegi neid rünnati.
</p>

<p>
Üks päev saatis nüüdseks surnud Jarl Haalad enda poja itta Russide maale hunniku loomanahkade ja relvadega, et ta tuleks sealt tagasi toiduga, mida tema nälgival rahval vaja oli. Kuu aega hiljem jõudis Jarlile teade, et tema poeg oli röövitud paljaks ning pea teiba otsa pandud. Jarl, kellel oli niigi palju muresid enda rahva ohjeldamisega, sai nii kurjas, et ta kuulutas rahvale <i>Me lähme Russide juurde! Tapame kõik kes vastu hakkavad! Võtame ellujäänud orjadeks! Saame toitu veel mitmeks talveks!</i> Ta kutsus rahvast üles minema piraadiretkele. Skandinaavialaste keeles kutsuti seda minema Viikingile.
</p>

<div class="center">
  <%= image_tag("beginning_of_raids.jpg") =%>
</div>

<p>
Jarl Haaladi reidid olid nii edukad, et tema rahvas rikkus ning tema mõjuvõim hakkas kiirelt üle Skandinaavia kasvama. Ei võtnud palju aega, et ka teised Jarlid hakkasid tema jälgedes käima. Sellest sai alguse viikingi ajastu.
</p>

<p>
Ajal, mil mängijad alustavad on Viikingi ajastu juba 300 aastat kestnud. Viikingid on idas kardetud piraadid, kes tulevad ootamatult ning rüüstavad külasid, templeid, kirikuid ja vahel isegi losse. Keegi ei vaata enam viikingitele ülevalt alla. Viikingeid kardetakse, austatakse ning vihatakse. Tõsi ta on -  viikingite reidid on olnud nii edukad, et viikingite maid loetakse rikkamaks kui kunagisi rikkaid idamaid. Selline seis on hakanud viikingitele vaikselt tagasi tooma vahepeal unustatud probleeme - nimelt maad on vähe, süüa on vähe ja enam pole naabritelt ka võtta väga..
</p>

<p>
Mõni Jarl on hakanud väljapääsu otsimiseks hakanud tegema sügavamaid reide itta - aga need retked on ohtlikumad ning senimaani pole sügavamal idas väga palju rikkamaid maid leitud. Mõni üksik puhtahull Jarl on võtnud ette retke ka läände - üle ookeani. Enamus neist ei ole tagasi tulnud. Need kes on, räägivad lõputust sinisest ja rahutust merest.
</p>

app/views/static_pages/homerules.html.erb
<div class="center">
  <%= image_tag("homerules.jpg") =%>
</div>

<h1>General:</h1>
<p>
  <ul>
    <li>If somebody is flanked, he is flanked by everybody</li>
    <li>If you want to move out of threatened square with move action, its DC 15 acrobatics check. If you wanto to move through enemy square, its a contest of acrobatics check</li>
    <li>Inspiration does not carry over to the next game</li>
    <li>1 interactioniga võib tõmmata 2 relva välja kui mõlemad käed vabad</li>
    <li>Drinking any potion is an interaction</li>
    <li>
    DISARM <br/>
    A creature can use a weapon attack to knock a weapon or another item from a target's grasp. The attacker makes an attack roll contested by the target's Strength (Athletics) check or Dexterity (Acrobatics) check. If the attacker wins the contest, the attack causes no damage or other ill effect, but the defender drops the item. The attacker can choose a location in 15 foot radius where the item drops.<br/>
    The attacker has disadvantage on its attack roll if the target is holding the item with two or more hands or if he doesnt have a weapon of his own(unless he has Martial arts or unarmed feat).<br/>
    The target has advantage on its ability check if it is larger than the attacking creature, or disadvantage if it is smaller.</li>
    <li>
    DISARM AND TAKE WEAPON <br/>
    A creature can use a weapon attack to knock a weapon or another item from a target's grasp. The attacker makes an attack roll contested by the target's Strength (Athletics) check or Dexterity (Acrobatics) check. The attacker has disadvantage on its attack roll and needs a free hand to take the weapon. If the attacker wins the contest, the attack causes no damage or other ill effect, but takes away the weapon of defender.
    </li>
  </ul>
</p>

app/views/static_pages/map.html.erb
<script>
function showPicture() {
  $("#selvarin").elevateZoom(
    {
      zoomType : "lens",
      lensShape : "round",
      lensSize : 800
    }
    );
  $("#loading-bar").hide();
  $("#picture-holder").show();
}
</script>
<div style="display:none">
  <img id="big-picture" src="/assets/selvarin.jpg" onload="showPicture()">
</div>
<div id="loading-bar">
  <div class="spinner"></div>
</div>
<div id="picture-holder" style="display:none">
  <%= image_tag("selvarin_thumb.jpg", id: "selvarin", data: {'zoom-image' => "/assets/selvarin.jpg"}) =%>
</div>
<p>
  <h1><a href="/assets/selvarin.jpg">FULL IMAGE<a></h1>
</p>